version: "3.9"  # optional since v1.27.0
services:
  cryptoviz-app:
    env_file: .env
    build: .
    ports:
      - "3001:5000"
    depends_on: 
      - cryptoviz-database
      - cryptoviz-redis
  cryptoviz-database:
    env_file: .env
    image: mysql:5.7.35
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
      - MYSQL_USER=${SQL_USERNAME}
      - MYSQL_PASSWORD=${SQL_USER_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
  cryptoviz-redis:
    env_file: .env
    image: redis:6.2.5
    ports:
      - "${REDIS_PORT}:6379"
  cryptoviz-phpmyadmin:
    env_file: .env
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=cryptoviz-database
      - PMA_USER=${SQL_USERNAME}
      - PMA_PASSWORD=${SQL_PASSWORD}
    ports:
      - "8081:80"
volumes:
   mysql-data:
