version: "3.9"  # optional since v1.27.0
services:
  cryptoviz-app:
    env_file: .env.production
    build: .
    ports:
      - "3001:5000"
    depends_on:
      - cryptoviz-database
      - cryptoviz-redis
    networks:
      - cryptoviz-network
  cryptoviz-database:
    env_file: .env.production
    image: mysql:5.7.35
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$SQL_PASSWORD
      - MYSQL_USER=$SQL_USERNAME
      - MYSQL_PASSWORD=$SQL_USER_PASSWORD
      - MYSQL_DATABASE=$SQL_DATABASE
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - cryptoviz-network
  cryptoviz-redis:
    env_file: .env.production
    image: redis:6.2.5
    ports:
      - "6379:6379"
    networks:
      - cryptoviz-network
  cryptoviz-phpmyadmin:
    env_file: .env.production
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=cryptoviz-database
      - PMA_USER=$SQL_USERNAME
      - PMA_PASSWORD=$SQL_PASSWORD
    ports:
      - "8081:80"
    networks:
      - cryptoviz-network
volumes:
   mysql-data:
networks:
   cryptoviz-network:
      driver: bridge